In [70]:
import pandas as pd
import numpy as np

In [71]:
D001_CSV_PATH = './d001.csv'

df = pd.read_csv(D001_CSV_PATH)

df

,년도,합계,자성대부두,신선대부두,감만부두,우암부두,감천한진,신감만부두,일반부두,신항1부두,신항2부두,신항3부두,신항4부두,신항5부두,다목적부두등
0,1994,48140,0,0,0,0,0,0,48140,0,0,0,0,0,0
1,1995,59775,0,622,0,0,0,0,59153,0,0,0,0,0,0
2,1996,4809217,1673341,1302513,0,21171,0,0,1812192,0,0,0,0,0,0
3,1997,5246646,1757757,1413847,23,316902,11848,0,1746269,0,0,0,0,0,0
4,1998,5701360,1096650,1121949,891424,281571,348910,0,1960856,0,0,0,0,0,0
5,1999,6555803,995119,1160577,1458472,355761,449766,0,2136108,0,0,0,0,0,0
6,2000,7729508,1304180,1281914,1887418,342486,403174,0,2510336,0,0,0,0,0,0
7,2001,8073125,1272333,1319812,1922622,447704,432972,0,2677682,0,0,0,0,0,0
8,2002,9453858,1534639,1528424,2261533,502460,504269,481202,2641331,0,0,0,0,0,0
9,2003,10408238,1584468,1786165,2546451,533298,512285,745613,2699958,0,0,0,0,0,0
10,2004,11492416,1825568,1994931,2723891,549967,548111,976348,2873600,0,0,0,0,0,0
11,2005,11843166,2126618,1962001,2862251,577392,497693,1098625,2718586,0,0,0,0,0,0
12,2006,12038607,2212473,2054646,2558765,548082,503673,1144700,2778554,237714,0,0,0,0,0
13,2007,13265127,2275402,2400910,2842963,531409,574824,1250360,2809608,446121,133530,0,0,0,0
14,2008,13454506,2103063,2282941,2722509,564691,556152,1210606,3202849,518839,292775,0,0,0,81
15,2009,11965485,1898370,2655797,2076156,552024,43283,1166042,888759,965591,796830,922419,0,0,214
16,2010,14158214,1581497,2688412,1873341,612496,1186,1228348,707637,701124,2389293,1533368,837088,0,4424
17,2011,16076550,1479816,2570889,1803991,640339,187,1240871,661029,928205,3213108,1952505,1576776,21,8813
18,2012,17046181,1286489,2372698,1628853,569922,468,1141941,603117,1220233,3280017,2442636,1988675,459969,51163
19,2013,17686100,1366534,1744861,1465206,514920,264,1032732,598215,1747307,3299457,2375614,2391890,1099366,49734
20,2014,18683288,1476998,2190665,1136003,46862,2579,1185608,678177,1712729,3895202,2467741,2552383,1305610,32731
21,2015,19468725,1729414,2015853,1132395,2718,3234,1110635,596629,2420860,4296221,2555966,2320661,1261535,22604
22,2016,19456292,1867428,1954293,1171826,2465,1880,1069650,527801,2418702,4626435,1925545,2322166,1541859,26242
23,2017,20493479,2073695,2260708,1286369,538,1146,943275,447729,2689256,4531302,2219402,2069198,1940079,30782
24,2018,21662573,1926182,2490203,1287910,1476,624,970504,320429,2477785,4938446,2770535,2061131,2269682,147666
25,2019,21992001,1923735,2404009,1444404,329,1427,1008637,178400,2295359,5501091,2783576,2167478,2119075,164481
26,2020,21823997,1826714,2307478,1509062,232,1855,1033422,166895,2743856,4837172,2954267,2110318,2131414,201312
27,2021,22706131,1982803,2376489,1498394,0,1012,1016701,287905,2737054,5086577,2939071,2237903,2315414,226808
28,2022,22078196,1917869,2341909,1424086,0,518,890661,255386,2684136,4827307,2672948,2257767,2433623,371986
29,2023,23153511,1855791,2534951,1400828,0,622,855699,196556,2859977,4934689,2790461,2390656,2496909,836372
30,2024,24402022,1443380,2813335,1543293,0,872,468279,252367,3018315,4957906,3076160,2560274,2422973,1844868

In [72]:
df.head()

,년도,합계,자성대부두,신선대부두,감만부두,우암부두,감천한진,신감만부두,일반부두,신항1부두,신항2부두,신항3부두,신항4부두,신항5부두,다목적부두등
0,1994,48140,0,0,0,0,0,0,48140,0,0,0,0,0,0
1,1995,59775,0,622,0,0,0,0,59153,0,0,0,0,0,0
2,1996,4809217,1673341,1302513,0,21171,0,0,1812192,0,0,0,0,0,0
3,1997,5246646,1757757,1413847,23,316902,11848,0,1746269,0,0,0,0,0,0
4,1998,5701360,1096650,1121949,891424,281571,348910,0,1960856,0,0,0,0,0,0

In [73]:
df.shape

(31, 15)

In [74]:
df.dtypes   #결측치 없을것으로 예상

년도        int64
합계        int64
자성대부두     int64
신선대부두     int64
감만부두      int64
우암부두      int64
감천한진      int64
신감만부두     int64
일반부두      int64
신항1부두     int64
신항2부두     int64
신항3부두     int64
신항4부두     int64
신항5부두     int64
다목적부두등    int64
dtype: object

In [75]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   년도      31 non-null     int64
 1   합계      31 non-null     int64
 2   자성대부두   31 non-null     int64
 3   신선대부두   31 non-null     int64
 4   감만부두    31 non-null     int64
 5   우암부두    31 non-null     int64
 6   감천한진    31 non-null     int64
 7   신감만부두   31 non-null     int64
 8   일반부두    31 non-null     int64
 9   신항1부두   31 non-null     int64
 10  신항2부두   31 non-null     int64
 11  신항3부두   31 non-null     int64
 12  신항4부두   31 non-null     int64
 13  신항5부두   31 non-null     int64
 14  다목적부두등  31 non-null     int64
dtypes: int64(15)
memory usage: 3.8 KB

해당 파일은 31개의 연도와 15개의 열, 모든 열이 정수형, 결측값 없음
년도는 숫자로 저장은 되어있으나 합산 불필요=> 시간 축

결측이 없다와 0이 많은 것은 다른 의미

In [76]:
pd.DataFrame({'자료형': df.dtypes.astype('str'),
              '비결측수': df.notna().sum(),
              '결측수': df.isna().sum(),
              '결측률(%)': df.isna().mean()*100,
              '고유값 수': df.nunique(dropna=True)})   # ㅇㄷㅇㄷ

          자료형  비결측수  결측수  결측률(%)  고유값 수
년도      int64    31    0     0.0     31
합계      int64    31    0     0.0     31
자성대부두   int64    31    0     0.0     30
신선대부두   int64    31    0     0.0     31
감만부두    int64    31    0     0.0     29
우암부두    int64    31    0     0.0     26
감천한진    int64    31    0     0.0     29
신감만부두   int64    31    0     0.0     24
일반부두    int64    31    0     0.0     31
신항1부두   int64    31    0     0.0     20
신항2부두   int64    31    0     0.0     19
신항3부두   int64    31    0     0.0     17
신항4부두   int64    31    0     0.0     16
신항5부두   int64    31    0     0.0     15
다목적부두등  int64    31    0     0.0     18

In [77]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
년도,31.0,2.009000e+03,9.092121e+00,1994.0,2001.5,2009.0,2016.5,2024.0
합계,31.0,1.396878e+07,6.999841e+06,48140.0,8763491.5,13454506.0,19981102.0,24402022.0
자성대부두,31.0,1.593494e+06,5.343120e+05,0.0,1404957.0,1729414.0,1920802.0,2275402.0
신선대부두,31.0,1.913994e+06,7.026255e+05,0.0,1471135.5,2054646.0,2388699.5,2813335.0
감만부두,31.0,1.560014e+06,8.186354e+05,0.0,1229097.5,1498394.0,1999389.0,2862251.0
우암부두,31.0,2.747489e+05,2.608211e+05,0.0,433.5,316902.0,540690.0,640339.0
감천한진,31.0,1.743495e+05,2.374882e+05,0.0,623.0,1880.0,441369.0,574824.0
신감만부두,31.0,7.506600e+05,4.856746e+05,0.0,234139.5,976348.0,1126288.0,1250360.0
일반부두,31.0,1.291686e+06,1.102136e+06,48140.0,304167.0,678177.0,2575833.5,3202849.0
신항1부두,31.0,1.123328e+06,1.169519e+06,0.0,0.0,701124.0,2419781.0,3018315.0
신항2부두,31.0,2.123786e+06,2.238415e+06,0.0,0.0,796830.0,4578868.5,5501091.0
신항3부두,31.0,1.238136e+06,1.285071e+06,0.0,0.0,922419.0,2511853.5,3076160.0
신항4부두,31.0,1.027238e+06,1.118048e+06,0.0,0.0,0.0,2202690.5,2560274.0
신항5부두,31.0,7.676622e+05,1.002712e+06,0.0,0.0,0.0,1740969.0,2496909.0
다목적부두등,31.0,1.296865e+05,3.591327e+05,0.0,0.0,214.0,50448.5,1844868.0

In [78]:
total = df['합계']

total_band= pd.cut(total,[0,5_000_000,10_000_000,15_000_000,20_000_000, float('inf')], 
       labels=['500만 이하', '500만~1000만', '1000만~1500만', '1500만~2000만', '2000만초과'])
total_band

0         500만 이하
1         500만 이하
2         500만 이하
3      500만~1000만
4      500만~1000만
5      500만~1000만
6      500만~1000만
7      500만~1000만
8      500만~1000만
9     1000만~1500만
10    1000만~1500만
11    1000만~1500만
12    1000만~1500만
13    1000만~1500만
14    1000만~1500만
15    1000만~1500만
16    1000만~1500만
17    1500만~2000만
18    1500만~2000만
19    1500만~2000만
20    1500만~2000만
21    1500만~2000만
22    1500만~2000만
23        2000만초과
24        2000만초과
25        2000만초과
26        2000만초과
27        2000만초과
28        2000만초과
29        2000만초과
30        2000만초과
Name: 합계, dtype: category
Categories (5, str): ['500만 이하' < '500만~1000만' < '1000만~1500만' < '1500만~2000만' < '2000만초과']

In [79]:
stable = df[df['년도'].ge(2000)]

stable

,년도,합계,자성대부두,신선대부두,감만부두,우암부두,감천한진,신감만부두,일반부두,신항1부두,신항2부두,신항3부두,신항4부두,신항5부두,다목적부두등
6,2000,7729508,1304180,1281914,1887418,342486,403174,0,2510336,0,0,0,0,0,0
7,2001,8073125,1272333,1319812,1922622,447704,432972,0,2677682,0,0,0,0,0,0
8,2002,9453858,1534639,1528424,2261533,502460,504269,481202,2641331,0,0,0,0,0,0
9,2003,10408238,1584468,1786165,2546451,533298,512285,745613,2699958,0,0,0,0,0,0
10,2004,11492416,1825568,1994931,2723891,549967,548111,976348,2873600,0,0,0,0,0,0
11,2005,11843166,2126618,1962001,2862251,577392,497693,1098625,2718586,0,0,0,0,0,0
12,2006,12038607,2212473,2054646,2558765,548082,503673,1144700,2778554,237714,0,0,0,0,0
13,2007,13265127,2275402,2400910,2842963,531409,574824,1250360,2809608,446121,133530,0,0,0,0
14,2008,13454506,2103063,2282941,2722509,564691,556152,1210606,3202849,518839,292775,0,0,0,81
15,2009,11965485,1898370,2655797,2076156,552024,43283,1166042,888759,965591,796830,922419,0,0,214
16,2010,14158214,1581497,2688412,1873341,612496,1186,1228348,707637,701124,2389293,1533368,837088,0,4424
17,2011,16076550,1479816,2570889,1803991,640339,187,1240871,661029,928205,3213108,1952505,1576776,21,8813
18,2012,17046181,1286489,2372698,1628853,569922,468,1141941,603117,1220233,3280017,2442636,1988675,459969,51163
19,2013,17686100,1366534,1744861,1465206,514920,264,1032732,598215,1747307,3299457,2375614,2391890,1099366,49734
20,2014,18683288,1476998,2190665,1136003,46862,2579,1185608,678177,1712729,3895202,2467741,2552383,1305610,32731
21,2015,19468725,1729414,2015853,1132395,2718,3234,1110635,596629,2420860,4296221,2555966,2320661,1261535,22604
22,2016,19456292,1867428,1954293,1171826,2465,1880,1069650,527801,2418702,4626435,1925545,2322166,1541859,26242
23,2017,20493479,2073695,2260708,1286369,538,1146,943275,447729,2689256,4531302,2219402,2069198,1940079,30782
24,2018,21662573,1926182,2490203,1287910,1476,624,970504,320429,2477785,4938446,2770535,2061131,2269682,147666
25,2019,21992001,1923735,2404009,1444404,329,1427,1008637,178400,2295359,5501091,2783576,2167478,2119075,164481
26,2020,21823997,1826714,2307478,1509062,232,1855,1033422,166895,2743856,4837172,2954267,2110318,2131414,201312
27,2021,22706131,1982803,2376489,1498394,0,1012,1016701,287905,2737054,5086577,2939071,2237903,2315414,226808
28,2022,22078196,1917869,2341909,1424086,0,518,890661,255386,2684136,4827307,2672948,2257767,2433623,371986
29,2023,23153511,1855791,2534951,1400828,0,622,855699,196556,2859977,4934689,2790461,2390656,2496909,836372
30,2024,24402022,1443380,2813335,1543293,0,872,468279,252367,3018315,4957906,3076160,2560274,2422973,1844868

In [80]:
stable['합계'].pct_change().dropna()

7     0.044455
8     0.171028
9     0.100951
10    0.104165
11    0.030520
12    0.016502
13    0.101882
14    0.014276
15   -0.110671
16    0.183255
17    0.135493
18    0.060313
19    0.037540
20    0.056383
21    0.042040
22   -0.000639
23    0.053309
24    0.057047
25    0.015207
26   -0.007639
27    0.040420
28   -0.027655
29    0.048705
30    0.053923
Name: 합계, dtype: float64

In [81]:
pd.Series({'합계 산술평균': total.mean(),
           '중앙값' : total.median()})

total.describe()

count    3.100000e+01
mean     1.396878e+07
std      6.999841e+06
min      4.814000e+04
25%      8.763492e+06
50%      1.345451e+07
75%      1.998110e+07
max      2.440202e+07
Name: 합계, dtype: float64

In [82]:
terminal_col =[]

for col_name in df.columns:
    if col_name not in ['년도', '합계']:
        terminal_col.append(col_name)

print(terminal_col)

['자성대부두', '신선대부두', '감만부두', '우암부두', '감천한진', '신감만부두', '일반부두', '신항1부두', '신항2부두', '신항3부두', '신항4부두', '신항5부두', '다목적부두등']

In [83]:
new_port=[]

for col_name in df.columns:
    if col_name.startswith('신항'):
        new_port.append(col_name)

print(new_port)

['신항1부두', '신항2부두', '신항3부두', '신항4부두', '신항5부두']

In [84]:
df_1 = df.copy()

df[new_port].sum(axis=1)
#df[new_port].T.sum()

0            0
1            0
2            0
3            0
4            0
5            0
6            0
7            0
8            0
9            0
10           0
11           0
12      237714
13      579651
14      811614
15     2684840
16     5460873
17     7670615
18     9391530
19    10913634
20    11933665
21    12855243
22    12834707
23    13449237
24    14517579
25    14866579
26    14777027
27    15316019
28    14875781
29    15472692
30    16035628
dtype: int64

In [86]:
df_1['부두합계'] = df_1[terminal_col].T.sum()
df_1['신항합계'] = df_1[new_port].T.sum()
df_1['신항비중'] = df_1['신항합계']/df_1['부두합계']

df_1[['년도', '부두합계', '신항합계', '신항비중']]

      년도      부두합계      신항합계      신항비중
0   1994     48140         0  0.000000
1   1995     59775         0  0.000000
2   1996   4809217         0  0.000000
3   1997   5246646         0  0.000000
4   1998   5701360         0  0.000000
5   1999   6555803         0  0.000000
6   2000   7729508         0  0.000000
7   2001   8073125         0  0.000000
8   2002   9453858         0  0.000000
9   2003  10408238         0  0.000000
10  2004  11492416         0  0.000000
11  2005  11843166         0  0.000000
12  2006  12038607    237714  0.019746
13  2007  13265127    579651  0.043697
14  2008  13454506    811614  0.060323
15  2009  11965485   2684840  0.224382
16  2010  14158214   5460873  0.385704
17  2011  16076550   7670615  0.477131
18  2012  17046181   9391530  0.550946
19  2013  17686100  10913634  0.617074
20  2014  18683288  11933665  0.638735
21  2015  19468725  12855243  0.660302
22  2016  19456292  12834707  0.659669
23  2017  20493479  13449237  0.656269
24  2018  21662573  14517579  0.670169
25  2019  21992001  14866579  0.675999
26  2020  21823997  14777027  0.677100
27  2021  22706131  15316019  0.674532
28  2022  22078196  14875781  0.673777
29  2023  23153511  15472692  0.668265
30  2024  24402022  16035628  0.657143

24년도 최대치