# 축

In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.DataFrame({
    '국어' : [90, 80, 70],
    '영어' : [85, 75, 65],
    '수학' : [80, 70, 60],
}, index=['철수', '영희', '민수']
)

df

    국어  영어  수학
철수  90  85  80
영희  80  75  70
민수  70  65  60

In [ ]:
df.index #0

Index(['철수', '영희', '민수'], dtype='str')

In [ ]:
df.columns #1

Index(['국어', '영어', '수학'], dtype='str')

In [7]:
df.axes

[Index(['철수', '영희', '민수'], dtype='str'),
 Index(['국어', '영어', '수학'], dtype='str')]

In [9]:
df.mean(axis=1)

철수    85.0
영희    75.0
민수    65.0
dtype: float64

In [ ]:
df.T.sum() #필요에 따라 전치 사용('T'ranspose)

철수    255
영희    225
민수    195
dtype: int64

In [13]:
df.T.head(1).mean()

철수    90.0
영희    80.0
민수    70.0
dtype: float64

In [15]:
import pandas as pd

orders = pd.DataFrame(
    {
        "order_date": pd.to_datetime([
            "2026-08-01",
            "2026-08-02",
            "2026-08-03",
            "2026-08-04",
            "2026-08-05",
            "2026-08-06",
        ]),
        "customer": [
            "민준", "서연", "지우",
            "도윤", "하준", "수빈",
        ],
        "region": [
            "서울", "부산", "서울",
            "대전", "부산", "서울",
        ],
        "product": [
            "키보드", "모니터", "마우스",
            "키보드", "노트북", "모니터",
        ],
        "quantity": [2, 1, 3, 2, 1, 2],
        "unit_price": [
            45000,
            320000,
            25000,
            45000,
            1350000,
            320000,
        ],
        "paid": [
            True, True, False,
            True, True, False,
        ],
    },
    index=pd.Index(
        ["O001", "O002", "O003", "O004", "O005", "O006"],
        name="order_id",
    ),
)

orders["total_amount"] = (
    orders["quantity"] * orders["unit_price"]
)

orders

,order_date,customer,region,product,quantity,unit_price,paid,total_amount
order_id,,,,,,,,
O001,2026-08-01,민준,서울,키보드,2,45000,True,90000
O002,2026-08-02,서연,부산,모니터,1,320000,True,320000
O003,2026-08-03,지우,서울,마우스,3,25000,False,75000
O004,2026-08-04,도윤,대전,키보드,2,45000,True,90000
O005,2026-08-05,하준,부산,노트북,1,1350000,True,1350000
O006,2026-08-06,수빈,서울,모니터,2,320000,False,640000

In [16]:
orders.index

Index(['O001', 'O002', 'O003', 'O004', 'O005', 'O006'], dtype='str', name='order_id')

In [17]:
orders.columns

Index(['order_date', 'customer', 'region', 'product', 'quantity', 'unit_price',
       'paid', 'total_amount'],
      dtype='str')

In [ ]:
orders.loc['O002'] #행만 가저올수 있음 #1차원 자료구조

order_date      2026-08-02 00:00:00
customer                         서연
region                           부산
product                         모니터
quantity                          1
unit_price                   320000
paid                           True
total_amount                 320000
Name: O002, dtype: object

In [21]:
orders.loc['O002', 'customer'] #행과 열을 동시에 가져올수 있음

'서연'

In [24]:
orders.loc[['O001', 'O003'], ['customer', 'product']
] # 2차원 자료구조

         customer product
order_id
O001           민준     키보드
O003           지우     마우스

In [25]:
orders.loc['O002' : 'O005']

,order_date,customer,region,product,quantity,unit_price,paid,total_amount
order_id,,,,,,,,
O002,2026-08-02,서연,부산,모니터,1,320000,True,320000
O003,2026-08-03,지우,서울,마우스,3,25000,False,75000
O004,2026-08-04,도윤,대전,키보드,2,45000,True,90000
O005,2026-08-05,하준,부산,노트북,1,1350000,True,1350000

In [26]:
orders.loc['O002' : 'O005', 'region': 'unit_price']

         region product  quantity  unit_price
order_id
O002         부산     모니터         1      320000
O003         서울     마우스         3       25000
O004         대전     키보드         2       45000
O005         부산     노트북         1     1350000

In [31]:
orders.iloc[1:3, 0:3] #iloc 위치기반, 끝 포함

         order_date customer region
order_id
O002     2026-08-02       서연     부산
O003     2026-08-03       지우     서울

In [30]:
orders[1:3] #iloc 위치기반, 끝 미포함

,order_date,customer,region,product,quantity,unit_price,paid,total_amount
order_id,,,,,,,,
O002,2026-08-02,서연,부산,모니터,1,320000,True,320000
O003,2026-08-03,지우,서울,마우스,3,25000,False,75000

In [32]:
orders.at['O004', 'product'] #at은 단일값 접근에 최적화 되어있음

'키보드'

In [42]:
orders[(orders['quantity'] >2)& (orders['total_amount'] > 100000)][['product', 'quantity']]

Empty DataFrame
Columns: [product, quantity]
Index: []