# 데이터프레임 기초

In [2]:
import pandas as pd
import numpy as np

|메뉴|가격|판매량|
|---|---|---|
|아메리카노|4500|152|
|카페라떼|5000|98|
|바닐라라떼|5500|67|
|카푸치노|5000|45|

In [3]:
data = {
    "메뉴" : ["아메리카노", "카페라떼", "바닐라라떼", "카푸치노"],
    "가격" : [4500, 5000, 5500, 5000],
    '판매량': [152, 98, 63, 45] 
}

df = pd.DataFrame(data)
df

      메뉴    가격  판매량
0  아메리카노  4500  152
1   카페라떼  5000   98
2  바닐라라떼  5500   63
3   카푸치노  5000   45

In [4]:
type(df)

pandas.DataFrame

In [5]:
s= pd.Series([1,3,5,7,9])
df = pd.DataFrame({
    'A' : [1, 2, 3]})
print(df.ndim)  # ndim 속성으로 차원 확인

2

In [6]:
data = {
    'tracking_no' : ['A001', 'A002', 'A003', 'A004'],
    'destination' : ['서울', '부산', '대구', '광주'],
    'weight_kg' : [10, 20, 30, 40],
    'delivered' : [True, False, True, False]
}
df = pd.DataFrame(data)
df

  tracking_no destination  weight_kg  delivered
0        A001          서울         10       True
1        A002          부산         20      False
2        A003          대구         30       True
3        A004          광주         40      False

In [7]:
df.loc[0]  # 첫 번째 행 선택

tracking_no    A001
destination      서울
weight_kg        10
delivered      True
Name: 0, dtype: object

In [8]:
pd.DataFrame(df.loc[0])

                0
tracking_no  A001
destination    서울
weight_kg      10
delivered    True

In [9]:
df.shape

(4, 4)

In [10]:
data = {
    'product' : ['노트북', '모니터', '키보드'],
    'quntity' : [1, 2, 3],
    'price' : [135000, 280000, 30000]
}
product_df = pd.DataFrame(data)
product_df

print(product_df.index)
print(product_df.columns)

products= pd.DataFrame(data, index=['p001', 'p002', 'p003'])

products

RangeIndex(start=0, stop=3, step=1)
Index(['product', 'quntity', 'price'], dtype='str')

     product  quntity   price
p001     노트북        1  135000
p002     모니터        2  280000
p003     키보드        3   30000

In [11]:
product =  ['노트북', '모니터', '키보드']
quantity = [1, 2, 3]
price = [135000, 280000, 30000]

data = {
    'product': product,
    'quantity': quantity,
    'price': price  

}

df= pd.DataFrame(data)

df

  product  quantity   price
0     노트북         1  135000
1     모니터         2  280000
2     키보드         3   30000

In [26]:
product_col = df['product']
product_col

total_price = df['quantity'] * df['price']

df['total_price']= total_price

df

  product  quantity   price  total_price
0     노트북         1  135000       135000
1     모니터         2  280000       560000
2     키보드         3   30000        90000

In [13]:
df[ ['quantity', 'price']  ]

df.dtypes

product       str
quantity    int64
price       int64
dtype: object

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   product   3 non-null      str
 1   quantity  3 non-null      int64
 2   price     3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 231.0 bytes

In [15]:
df.T

               0       1      2
product      노트북     모니터    키보드
quantity       1       2      3
price     135000  280000  30000

In [16]:
import pandas as pd
import numpy as np

orders = pd.DataFrame(
    {
        "order_date": pd.to_datetime([
            "2026-08-01", "2026-08-01", "2026-08-02", "2026-08-03",
            "2026-08-04", "2026-08-05", "2026-08-05", "2026-08-06",
            "2026-08-07", "2026-08-08", "2026-08-09", "2026-08-10",
        ]),
        "customer": pd.Series(
            ["민준", "서연", "지우", "도윤", "하준", "서연",
             "민준", "지우", "도윤", "하준", "민준", "서연"],
            dtype="string",
        ),
        "region": pd.Series(
            ["서울", "부산", "서울", "대전", "부산", "서울",
             "대전", "서울", "부산", "대전", "서울", "부산"],
            dtype="category",
        ),
        "product": pd.Series(
            ["키보드", "모니터", "마우스", "키보드", "모니터", "키보드",
             "마우스", "모니터", "키보드", "마우스", "모니터", "키보드"],
            dtype="category",
        ),
        "quantity": pd.Series(
            [2, 1, 3, 2, 1, 4, 2, 1, 5, 2, 1, 3],
            dtype="Int64",
        ),
        "unit_price": [
            45000, 320000, 25000, 45000, 320000, 45000,
            25000, 320000, 45000, 25000, 320000, 45000,
        ],
        "discount_rate": [
            0.00, 0.10, np.nan, 0.05, 0.00, 0.10,
            0.00, np.nan, 0.05, 0.00, 0.10, 0.00,
        ],
        "paid": pd.Series(
            [True, True, False, True, True, True,
             False, True, True, pd.NA, True, False],
            dtype="boolean",
        ),
    },
    index=pd.Index(
        [f"O{i:03d}" for i in range(1, 13)],
        name="order_id",
    ),
)

orders["customer"] = pd.array(
    ["민준", "서연", "지우", "도윤", "하준", "서연",
     "민준", "지우", "도윤", "하준", "민준", "서연"],
    dtype="string",
)
orders["region"] = pd.Categorical(
    ["서울", "부산", "서울", "대전", "부산", "서울",
     "대전", "서울", "부산", "대전", "서울", "부산"]
)
orders["product"] = pd.Categorical(
    ["키보드", "모니터", "마우스", "키보드", "모니터", "키보드",
     "마우스", "모니터", "키보드", "마우스", "모니터", "키보드"]
)
orders["quantity"] = pd.array(
    [2, 1, 3, 2, 1, 4, 2, 1, 5, 2, 1, 3],
    dtype="Int64",
)
orders["paid"] = pd.array(
    [True, True, False, True, True, True,
     False, True, True, pd.NA, True, False],
    dtype="boolean",
)

print(orders)

         order_date customer region product  quantity  unit_price  \
order_id
O001     2026-08-01       민준     서울     키보드         2       45000
O002     2026-08-01       서연     부산     모니터         1      320000
O003     2026-08-02       지우     서울     마우스         3       25000
O004     2026-08-03       도윤     대전     키보드         2       45000
O005     2026-08-04       하준     부산     모니터         1      320000
O006     2026-08-05       서연     서울     키보드         4       45000
O007     2026-08-05       민준     대전     마우스         2       25000
O008     2026-08-06       지우     서울     모니터         1      320000
O009     2026-08-07       도윤     부산     키보드         5       45000
O010     2026-08-08       하준     대전     마우스         2       25000
O011     2026-08-09       민준     서울     모니터         1      320000
O012     2026-08-10       서연     부산     키보드         3       45000

          discount_rate   paid
order_id
O001               0.00   True
O002               0.10   True
O003                NaN  False
O004               0.05   True
O005               0.00   True
O006               0.10   True
O007               0.00  False
O008                NaN   True
O009               0.05   True
O010               0.00   <NA>
O011               0.10   True
O012               0.00  False

In [17]:
orders.head(-1) #기본적으로 5개

,order_date,customer,region,product,quantity,unit_price,discount_rate,paid
order_id,,,,,,,,
O001,2026-08-01,민준,서울,키보드,2,45000,0.00,True
O002,2026-08-01,서연,부산,모니터,1,320000,0.10,True
O003,2026-08-02,지우,서울,마우스,3,25000,NaN,False
O004,2026-08-03,도윤,대전,키보드,2,45000,0.05,True
O005,2026-08-04,하준,부산,모니터,1,320000,0.00,True
O006,2026-08-05,서연,서울,키보드,4,45000,0.10,True
O007,2026-08-05,민준,대전,마우스,2,25000,0.00,False
O008,2026-08-06,지우,서울,모니터,1,320000,NaN,True
O009,2026-08-07,도윤,부산,키보드,5,45000,0.05,True
O010,2026-08-08,하준,대전,마우스,2,25000,0.00,<NA>
O011,2026-08-09,민준,서울,모니터,1,320000,0.10,True

In [18]:
orders.tail() #기본적으로 5개

,order_date,customer,region,product,quantity,unit_price,discount_rate,paid
order_id,,,,,,,,
O008,2026-08-06,지우,서울,모니터,1,320000,NaN,True
O009,2026-08-07,도윤,부산,키보드,5,45000,0.05,True
O010,2026-08-08,하준,대전,마우스,2,25000,0.00,<NA>
O011,2026-08-09,민준,서울,모니터,1,320000,0.10,True
O012,2026-08-10,서연,부산,키보드,3,45000,0.00,False

In [19]:
orders.sample(3, random_state=42) #기본적으로 1개, random_state는 임의의 숫자

,order_date,customer,region,product,quantity,unit_price,discount_rate,paid
order_id,,,,,,,,
O011,2026-08-09,민준,서울,모니터,1,320000,0.1,True
O010,2026-08-08,하준,대전,마우스,2,25000,0.0,<NA>
O001,2026-08-01,민준,서울,키보드,2,45000,0.0,True

In [20]:
orders.sample(frac=0.25)

,order_date,customer,region,product,quantity,unit_price,discount_rate,paid
order_id,,,,,,,,
O001,2026-08-01,민준,서울,키보드,2,45000,0.0,True
O003,2026-08-02,지우,서울,마우스,3,25000,NaN,False
O006,2026-08-05,서연,서울,키보드,4,45000,0.1,True

In [21]:
orders.describe()

                order_date  quantity     unit_price  discount_rate
count                   12      12.0      12.000000      10.000000
mean   2026-08-05 02:00:00      2.25  131666.666667       0.040000
min    2026-08-01 00:00:00       1.0   25000.000000       0.000000
25%    2026-08-02 18:00:00       1.0   40000.000000       0.000000
50%    2026-08-05 00:00:00       2.0   45000.000000       0.025000
75%    2026-08-07 06:00:00       3.0  320000.000000       0.087500
max    2026-08-10 00:00:00       5.0  320000.000000       0.100000
std                    NaN  1.288057  139338.262926       0.045947

In [22]:
orders[
    ['quantity', 'unit_price', 'discount_rate']
].describe()

       quantity     unit_price  discount_rate
count      12.0      12.000000      10.000000
mean       2.25  131666.666667       0.040000
std    1.288057  139338.262926       0.045947
min         1.0   25000.000000       0.000000
25%         1.0   40000.000000       0.000000
50%         2.0   45000.000000       0.025000
75%         3.0  320000.000000       0.087500
max         5.0  320000.000000       0.100000

In [23]:
orders.nunique()

order_date       10
customer          5
region            3
product           3
quantity          5
unit_price        3
discount_rate     3
paid              2
dtype: int64