In [1]:
import pandas as pd
import numpy as np

In [10]:
IRIS_CSV_PATH = './iris.csv'
IRIS_COL = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

In [11]:
df = pd.read_csv(IRIS_CSV_PATH,skiprows=1,header=None
                 ,names=IRIS_COL)
df.shape

(150, 5)

In [12]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

## 데이터 탐색의 목적

- 데이터의 구조
- 데이터의 결측값 유무
- 각 칼럼의 타입
- 수치의 범위

In [14]:
df.sample(frac=0.1)

     sepal_length  sepal_width  petal_length  petal_width  species
111           6.4          2.7           5.3          1.9        2
86            6.7          3.1           4.7          1.5        1
64            5.6          2.9           3.6          1.3        1
40            5.0          3.5           1.3          0.3        0
56            6.3          3.3           4.7          1.6        1
42            4.4          3.2           1.3          0.2        0
2             4.7          3.2           1.3          0.2        0
22            4.6          3.6           1.0          0.2        0
0             5.1          3.5           1.4          0.2        0
82            5.8          2.7           3.9          1.2        1
138           6.0          3.0           4.8          1.8        2
87            6.3          2.3           4.4          1.3        1
44            5.1          3.8           1.9          0.4        0
66            5.6          3.0           4.5          1.5        1
50            7.0          3.2           4.7          1.4        1

In [15]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species           int64
dtype: object

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

In [18]:
df.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [19]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width     species
count    150.000000   150.000000    150.000000   150.000000  150.000000
mean       5.843333     3.057333      3.758000     1.199333    1.000000
std        0.828066     0.435866      1.765298     0.762238    0.819232
min        4.300000     2.000000      1.000000     0.100000    0.000000
25%        5.100000     2.800000      1.600000     0.300000    0.000000
50%        5.800000     3.000000      4.350000     1.300000    1.000000
75%        6.400000     3.300000      5.100000     1.800000    2.000000
max        7.900000     4.400000      6.900000     2.500000    2.000000

### 기술통계의 목적

- 중심 경향치 : 데이터가 어디에 위치 => 평균, 중앙값 확인
- 최빈값 : 가장 높은 빈도
- 산포도 : 데이터의 분산 확인
 - 분산 : (평균-수치)^2의 평균
 - 표준편차 = std = 분산^1/2
 - 사분위수 : 전체 데이터를 4등분 위치의 값

- 분포의 형태
 - 왜도 : 분포의 치우친 정도
 - 첨도 : 분포의 뾰족한 정도

In [20]:
df['sepal_width'].median()

np.float64(3.0)

In [45]:
# setosa,versicolor,virginica

species_code = { 0: 'setosa', 1: 'versicolor', 2: 'virginica' }

species_df=df.copy() # 깊은 복사

species_df

     sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [22]:
df['species'].map(species_code)

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: str

In [24]:
species_df['species_code'] = df['species'].map(species_code)

species_df.head()

   sepal_length  sepal_width  petal_length  petal_width  species species_code
0           5.1          3.5           1.4          0.2        0       setosa
1           4.9          3.0           1.4          0.2        0       setosa
2           4.7          3.2           1.3          0.2        0       setosa
3           4.6          3.1           1.5          0.2        0       setosa
4           5.0          3.6           1.4          0.2        0       setosa

In [33]:
species_df.loc[species_df['species'] == 0]

    sepal_length  sepal_width  petal_length  petal_width  species species_code
0            5.1          3.5           1.4          0.2        0       setosa
1            4.9          3.0           1.4          0.2        0       setosa
2            4.7          3.2           1.3          0.2        0       setosa
3            4.6          3.1           1.5          0.2        0       setosa
4            5.0          3.6           1.4          0.2        0       setosa
5            5.4          3.9           1.7          0.4        0       setosa
6            4.6          3.4           1.4          0.3        0       setosa
7            5.0          3.4           1.5          0.2        0       setosa
8            4.4          2.9           1.4          0.2        0       setosa
9            4.9          3.1           1.5          0.1        0       setosa
10           5.4          3.7           1.5          0.2        0       setosa
11           4.8          3.4           1.6          0.2        0       setosa
12           4.8          3.0           1.4          0.1        0       setosa
13           4.3          3.0           1.1          0.1        0       setosa
14           5.8          4.0           1.2          0.2        0       setosa
15           5.7          4.4           1.5          0.4        0       setosa
16           5.4          3.9           1.3          0.4        0       setosa
17           5.1          3.5           1.4          0.3        0       setosa
18           5.7          3.8           1.7          0.3        0       setosa
19           5.1          3.8           1.5          0.3        0       setosa
20           5.4          3.4           1.7          0.2        0       setosa
21           5.1          3.7           1.5          0.4        0       setosa
22           4.6          3.6           1.0          0.2        0       setosa
23           5.1          3.3           1.7          0.5        0       setosa
24           4.8          3.4           1.9          0.2        0       setosa
25           5.0          3.0           1.6          0.2        0       setosa
26           5.0          3.4           1.6          0.4        0       setosa
27           5.2          3.5           1.5          0.2        0       setosa
28           5.2          3.4           1.4          0.2        0       setosa
29           4.7          3.2           1.6          0.2        0       setosa
30           4.8          3.1           1.6          0.2        0       setosa
31           5.4          3.4           1.5          0.4        0       setosa
32           5.2          4.1           1.5          0.1        0       setosa
33           5.5          4.2           1.4          0.2        0       setosa
34           4.9          3.1           1.5          0.2        0       setosa
35           5.0          3.2           1.2          0.2        0       setosa
36           5.5          3.5           1.3          0.2        0       setosa
37           4.9          3.6           1.4          0.1        0       setosa
38           4.4          3.0           1.3          0.2        0       setosa
39           5.1          3.4           1.5          0.2        0       setosa
40           5.0          3.5           1.3          0.3        0       setosa
41           4.5          2.3           1.3          0.3        0       setosa
42           4.4          3.2           1.3          0.2        0       setosa
43           5.0          3.5           1.6          0.6        0       setosa
44           5.1          3.8           1.9          0.4        0       setosa
45           4.8          3.0           1.4          0.3        0       setosa
46           5.1          3.8           1.6          0.2        0       setosa
47           4.6          3.2           1.4          0.2        0       setosa
48           5.3          3.7           1.5          0.2        0       setosa
49           5.0          3.3           1.4          0.2        0       setosa

In [35]:
result = species_df.loc[species_df['species'] == 0]

result.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  50 non-null     float64
 1   sepal_width   50 non-null     float64
 2   petal_length  50 non-null     float64
 3   petal_width   50 non-null     float64
 4   species       50 non-null     int64
 5   species_code  50 non-null     str
dtypes: float64(4), int64(1), str(1)
memory usage: 2.8 KB

In [36]:
result.describe()

       sepal_length  sepal_width  petal_length  petal_width  species
count      50.00000    50.000000     50.000000    50.000000     50.0
mean        5.00600     3.428000      1.462000     0.246000      0.0
std         0.35249     0.379064      0.173664     0.105386      0.0
min         4.30000     2.300000      1.000000     0.100000      0.0
25%         4.80000     3.200000      1.400000     0.200000      0.0
50%         5.00000     3.400000      1.500000     0.200000      0.0
75%         5.20000     3.675000      1.575000     0.300000      0.0
max         5.80000     4.400000      1.900000     0.600000      0.0

In [26]:
species_df['species'].unique( )

array([0, 1, 2])

In [27]:
species_df['species'].value_counts()

species
0    50
1    50
2    50
Name: count, dtype: int64

In [28]:
species_df['species'].value_counts(normalize=True)

species
0    0.333333
1    0.333333
2    0.333333
Name: proportion, dtype: float64

In [38]:
df_ng = df.head(5).copy()

df_ng['sepal_length'] = df_ng['sepal_length'].astype('str')

df_ng.loc[2, 'sepal_length'] = 'unknown'


df_ng

  sepal_length  sepal_width  petal_length  petal_width  species
0          5.1          3.5           1.4          0.2        0
1          4.9          3.0           1.4          0.2        0
2      unknown          3.2           1.3          0.2        0
3          4.6          3.1           1.5          0.2        0
4          5.0          3.6           1.4          0.2        0